# Pandas

# Def: Pandas is a Open source library designed for Data Manipulation and Analysis.

# Pandas is designed over the Numpy.

# Important list of operation in Pandas

1. Data Structure creation (Series (1D array), DataFrame (2d array))
2. Data input and output (CSV, EXCEL, SQL, JSON)
3. Understanding the Dataset (head, tail, dtype....)
4. Data Filtering and Indexing (loc, iloc, where(),...)
5. Handling of Missing values(NaN/Null)
6. Removing Duplicate values
7. Handling inconsistant data
8. Data transformation using apply(), map()
9. Aggregation and Grouping
10. Time Series operations
11. Basic Data visualization

# Importing and installation of pandas

In [1]:
# pip install pandas
# Above command can create problem with old numpy version

# conda install pandas
# conda command will update numpy also with pandas. So no issue.

import pandas as pd

In [2]:
pd.__version__

'2.2.3'

# 1. Data Structure creation (Series (1D array), DataFrame (2d array))

#### Series (1D array)

In [3]:
# create series
ser1 = pd.Series()
print(ser1)

Series([], dtype: object)

In [4]:
# convert the list to Series
list1 = [10, 20, 30, 40, 50]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
# convert the list to Series
list1 = [10, 20, 30, 40, 50,"Hello"]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

# In pandas strings are represented as object
# IMP: In Series, all elements have the same datatype

0       10
1       20
2       30
3       40
4       50
5    Hello
dtype: object
<class 'pandas.core.series.Series'>

In [6]:
# Example-2 : convert tuple to Series
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))
print(ser2[-2])

# In Pandas Series, direct negative indexing not allowed.

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

KeyError: -2

In [ ]:
# set cannot be converted to pandas series
# set is unordered and Series is ordered, so no conversion
set1 = {10, 20, 30, 40, 50}
ser2 = pd.Series(set1)
print(ser2)

In [ ]:
# Convert the numpy array into Series
import numpy as np

arr1 = np.array([10,20,30,40,50])
print(arr1, type(arr1))

ser3 = pd.Series(arr1, index = ['a', 'b', 'c', 'd', 'e'])
print(ser3, type(ser3))
print(ser3['a'])

In [ ]:
# update operation on series
ser2[3] = 100000

# Insert new value
ser2[5] = 2000
ser2['a'] = 5000
ser2[60] = 7000
ser2[3.4] = 9000

In [ ]:
print(ser2)

In [ ]:
# delete element from series
ser2 = ser2.drop(1)
ser2

# DataFrame (2d array)

In [7]:
# Data frame is a 2D array, store data in form of matrix.

#### creating dataframe

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []

In [12]:
# converting list to data frame
fruits_list = ["AratiPandu", "MamadiPandu", "KamalaPandu", "DrakshaPandu"]

df = pd.DataFrame(fruits_list, columns = ["Fruit Name"])
df

     Fruit Name
0    AratiPandu
1   MamadiPandu
2   KamalaPandu
3  DrakshaPandu

In [13]:
# converting 2D list to DataFrame

fruits_list = [["AratiPandu",40], ["MamadiPandu", 1000], ["KamalaPandu", 10], ["DrakshaPandu",120]]

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price"])
df

     Fruit Name  Price
0    AratiPandu     40
1   MamadiPandu   1000
2   KamalaPandu     10
3  DrakshaPandu    120

In [14]:
# created 3 columns dataframe (List of List)
fruits_list = [["AratiPandu",40,100], ["MamadiPandu", 1000, 200], ["KamalaPandu", 10, 1000], ["DrakshaPandu",120, -100]]

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

     Fruit Name  Price  Discount
0    AratiPandu     40       100
1   MamadiPandu   1000       200
2   KamalaPandu     10      1000
3  DrakshaPandu    120      -100

In [15]:
# Create DataFrame from List of Tuple

fruits_list = [("AratiPandu",40,100), ("MamadiPandu", 1000, 200), ("KamalaPandu", 10, 1000), ("DrakshaPandu",120, -100)]

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

     Fruit Name  Price  Discount
0    AratiPandu     40       100
1   MamadiPandu   1000       200
2   KamalaPandu     10      1000
3  DrakshaPandu    120      -100

In [16]:
# Convert the set of tuples into DataFrame

fruits_list = {("AratiPandu",40,100), ("MamadiPandu", 1000, 200), ("KamalaPandu", 10, 1000), ("DrakshaPandu",120, -100)}

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

     Fruit Name  Price  Discount
0    AratiPandu     40       100
1   KamalaPandu     10      1000
2   MamadiPandu   1000       200
3  DrakshaPandu    120      -100

In [18]:
# Creating Dataframe from Set of Set

# In set, we cannot store the Mutable items
# In set, Only immutable items can be store

fruits_list = {["AratiPandu",40,100], ["MamadiPandu", 1000, 200], ["KamalaPandu", 10, 1000], ["DrakshaPandu",120, -100]}

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

TypeError: unhashable type: 'list'

In [20]:
# Creating DataFrame from Dictionary

student_data = {
    "Name" : ["Shiva", "Niranjan", "Suresh", "Akash", "Lahari", "Rakesh"],
    "Salary" : [40, 50, 60, 15, 25, 100],
    "Study_time" : [12, 14, 16, 1, 5, 24]
}

df1 = pd.DataFrame(student_data)
df1

       Name  Salary  Study_time
0     Shiva      40          12
1  Niranjan      50          14
2    Suresh      60          16
3     Akash      15           1
4    Lahari      25           5
5    Rakesh     100          24

# 2. Data input and output (CSV, EXCEL, SQL, JSON)

In [21]:
# importing data from CSV file

import os
os.getcwd()

'C:\\Users\\Prikshit_Ishi\\Complete_Data_Science\\Pandas'

In [22]:
# import a CSV file as DataFrame
df_csv = pd.read_csv("CSV_data.csv")
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [23]:
# Import excel file as a Dataframe

df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [24]:
# Export the data back to CSV and Excel file

df_csv.to_excel("Da22_excel.xlsx", index = False)

df.to_csv("DA22_CSV.csv", index = False)